#!/usr/bin/env node
/* Generates supabase/seed.sql from the same js/permissions.js and js/data.js
   the portal itself uses, so the database, the Node server and the browser
   can never hold three different ideas of who may do what.

     node tools/build_sql.js > supabase/seed.sql                              */

const path = require("node:path");
const ROOT = path.resolve(__dirname, "..");
const P = require(path.join(ROOT, "js", "permissions.js"));
const D = require(path.join(ROOT, "js", "data.js"));

const q = (v) => `'${String(v).replace(/'/g, "''")}'`;
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const out = [];

const today = process.argv[2] || new Date().toISOString().slice(0, 10);
const seed = D.buildSeed(today);
/* Each account gets its own temporary password, printed to stderr once so it
   never ends up committed alongside the seed. */
const WORDS = ["acacia", "baobab", "sunrise", "marula", "granite", "msasa", "falls", "ridge", "kopje", "aloe", "matopo", "ebony"];
const crypto = require("node:crypto");
const tempPassword = () => `${WORDS[crypto.randomInt(WORDS.length)]}-${WORDS[crypto.randomInt(WORDS.length)]}-${crypto.randomInt(100, 999)}`;

out.push(`-- Generated by tools/build_sql.js on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.`);
out.push(`-- Run supabase/schema.sql first, then this file.`);
out.push(`begin;`);
out.push(`truncate records, settings, changes, sessions, credentials, role_permissions, locked_permissions, role_tiers, gate_attempts;`);

/* role -> permission, straight from the shared catalogue */
out.push(`\n-- who may do what, by role`);
for (const role of Object.keys(P.ROLES)) {
  for (const perm of P.roleDefaultPerms(role)) out.push(`insert into role_permissions values (${q(role)}, ${q(perm)});`);
}
const locked = P.PERMISSION_GROUPS.flatMap(g => g.perms.filter(p => p.locked).map(p => p.key));
out.push(`\n-- permissions that follow the role and cannot be granted sideways`);
for (const p of locked) out.push(`insert into locked_permissions values (${q(p)});`);

/* The tier is what stops an account being issued upwards, so the database
   needs it as well as the interface. */
out.push(`\n-- role tiers, which decide who may set up an account for whom`);
for (const [role, r] of Object.entries(P.ROLES)) {
  out.push(`insert into role_tiers values (${q(role)}, ${r.tier}, ${!!r.governance});`);
}

/* single documents */
const SETTINGS = ["school", "classes", "teams", "timetable", "gradeScale", "feeItems", "feeRules",
  "docCategories", "commTemplates", "intakes", "strategy", "reads"];
out.push(`\n-- the school's settings`);
for (const key of SETTINGS) if (seed[key] !== undefined) out.push(`insert into settings (key, data) values (${q(key)}, ${j(seed[key])});`);

/* The family portal is assembled in SQL, so the handful of constants
   js/family.js reads from js/data.js have to be in the database too — the
   school day, the weekday names, which subjects carry a mark, and how the
   kinds of assessment are weighted. Written from the same source, so the two
   cannot drift. */
out.push(`\n-- constants the family portal's read needs, from js/data.js`);
out.push(`insert into settings (key, data) values ('periods', ${j(D.PERIODS)});`);
out.push(`insert into settings (key, data) values ('dayLabels', ${j(D.DAY_LABELS)});`);
out.push(`insert into settings (key, data) values ('assessed', ${j(D.ASSESSED)});`);
out.push(`insert into settings (key, data) values ('assessmentKinds', ${j(D.ASSESSMENT_KINDS)});`);

/* record collections */
const COLLECTIONS = ["staff", "guardians", "pupils", "attendance", "absences", "messages", "channels",
  "documents", "events", "welfare", "vacancies", "candidates", "applicants", "assessments", "invoices",
  "payments", "comms", "alumni", "integrations", "board", "statutory", "budget", "projects", "audit"];
out.push(`\n-- the school`);
for (const collection of COLLECTIONS) {
  const value = seed[collection];
  if (!value) continue;
  const rows = Array.isArray(value)
    ? value.map((r, i) => [String(r.id ?? `${collection}_${i}`), r])
    : Object.entries(value);
  for (const [id, row] of rows) {
    const clean = { ...row }; delete clean.pin;
    out.push(`insert into records (collection, id, data) values (${q(collection)}, ${q(id)}, ${j(clean)});`);
  }
}

/* credentials — bcrypt is computed by Postgres so no hash is written here */
out.push(`\n-- starting passwords, hashed by the database and marked must-change`);
const issued = [];
for (const s of D.STAFF) {
  const password = tempPassword();
  issued.push([s.email, password, `${s.title} ${s.first} ${s.last}`]);
  out.push(`insert into credentials (staff_id, password_hash, must_change) values (${q(s.id)}, crypt(${q(password)}, gen_salt('bf', 12)), true);`);
}
process.stderr.write("\nTemporary passwords — hand these over in person; they are not in the SQL:\n\n");
for (const [email, password, name] of issued) process.stderr.write(`  ${email.padEnd(42)} ${password}   (${name})\n`);
process.stderr.write("\n");

out.push(`\ncommit;`);
out.push(`-- ${COLLECTIONS.reduce((n, c) => n + (Array.isArray(seed[c]) ? seed[c].length : Object.keys(seed[c] || {}).length), 0)} records, ${D.STAFF.length} accounts.`);
process.stdout.write(out.join("\n") + "\n");
